version: "3.9"
name: pei_dev
services:
  annuaire_db_2:
    container_name: annuaire_db_2
    image: "postgres:15.4"
    volumes:
      - ./databases/annuaire:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${ANNUAIRE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ANNUAIRE_POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      POSTGRES_HOST: annuaire_db_2
    networks:
      icc_net:
        ipv4_address: 192.168.11.10
    ports:
      - "5433:5432"
  
  gateway:
      build: 
        context: ./
        target: gateway
      #image: djedou/icc_gateway:v_0.3.3
      container_name: gateway
      networks:
        icc_net:
          ipv4_address: 192.168.11.12
      ports:
        - 4012:4012
      environment:
        - GatewayAddress=192.168.11.12:4012
        - AnnuaireClientAddress=192.168.11.14:4014
      depends_on:
        - annuaire
  
  annuaire:
      build: 
        context: ./
        target: annuaire
      #image: djedou/icc_annuaire:v_0.3.3
      container_name: annuaire
      networks:
        icc_net:
          ipv4_address: 192.168.11.14
      ports:
        - 4014:4014
      environment:
        - AnnuaireClientAddress=192.168.11.14:4014
        - AnnuaireDatabaseAddressPostgres=postgres://${ANNUAIRE_POSTGRES_USER}:${ANNUAIRE_POSTGRES_PASSWORD}@annuaire_db_2:5432/postgres
      depends_on:
        - annuaire_db_2

networks:
  icc_net:
    ipam:
      driver: default
      config:
          - 
            subnet: "192.168.11.0/24"