version: "3.9"
name: pei
services:
  annuaire_db:
    container_name: annuaire_db
    image: "postgres:15.4"
    volumes:
      - ./databases/annuaire:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${ANNUAIRE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ANNUAIRE_POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
      POSTGRES_HOST: annuaire_db
    networks:
      icc_net:
        ipv4_address: 192.168.10.10
    ports:
      - "5433:5432"
  
  icc_gateway:
      build: 
        context: ./
        target: gateway_runtime
      image: djedou/icc_gateway:v_0.3.3
      container_name: icc_gateway
      networks:
        icc_net:
          ipv4_address: 192.168.10.12
      ports:
        - 4012:4012
      environment:
        - GatewayAddress=192.168.10.12:4012
        - AnnuaireClientAddress=192.168.10.14:4014
        - AnnuaireDatabaseAddress=postgres://${ANNUAIRE_POSTGRES_USER}:${ANNUAIRE_POSTGRES_PASSWORD}@${ANNUAIRE_POSTGRES_IP}:5433/postgres
      depends_on:
        - annuaire_db


networks:
  icc_net:
    ipam:
      driver: default
      config:
          - 
            subnet: "192.168.10.0/24"