mod campus;
mod departements;
mod competences;
mod diplomes_certificats;
mod domaines;
mod ecoles;
mod entreprises;
mod langues;
mod localite;
mod specialites;
mod titres;
mod user_plus_infos;
mod users;
mod user_contact;
mod user_campus;
mod user_competences;
mod user_department;
mod user_diplomes;
mod user_domaines;
mod user_ecoles;
mod user_entreprises;
mod user_langues;
mod user_localites;
mod user_specialites;
mod user_titres;
/*
pub(crate) use campus::*;
pub(crate) use departements::*;
pub(crate) use competences::*;
pub(crate) use diplomes_certificats::*;
pub(crate) use domaines::*;
pub(crate) use ecoles::*;
pub(crate) use entreprises::*;
pub(crate) use langues::*;
pub(crate) use localite::*;
pub(crate) use specialites::*;
pub(crate) use titres::*;
pub(crate) use user_plus_infos::*;
pub(crate) use users::*;
pub(crate) use user_contact::*;
pub(crate) use user_campus::*;
pub(crate) use user_competences::*;
pub(crate) use user_department::*;
pub(crate) use user_diplomes::*;
pub(crate) use user_domaines::*;
pub(crate) use user_ecoles::*;
pub(crate) use user_entreprises::*;
pub(crate) use user_langues::*;
pub(crate) use user_localites::*;
pub(crate) use user_specialites::*;
pub(crate) use user_titres::*;
*/

