mod search_stars;
mod create_campus;
mod create_competences;
mod create_departement;
mod create_diplomes;
mod create_domaine;
mod create_ecole;
mod create_entreprise;
mod create_langue;
mod create_localite;
mod create_specialite;
mod create_titre;
mod create_user_info;
mod create_user;

pub use search_stars::*;
pub use create_campus::*;
pub use create_competences::*;
pub use create_departement::*;
pub use create_diplomes::*;
pub use create_domaine::*;
pub use create_ecole::*;
pub use create_entreprise::*;
pub use create_langue::*;
pub use create_localite::*;
pub use create_specialite::*;
pub use create_titre::*;
pub use create_user_info::*;
pub use create_user::*;
