mod campus;
mod departements;
mod competences;
mod diplomes_certificats;
mod domaines;
mod ecoles;
mod entreprises;
mod langues;
mod localite;
mod specialites;
mod titres;
mod user_plus_infos;
mod users;
mod user_contact;
mod user_campus;
mod user_competences;
mod user_department;
mod user_diplomes;
mod user_domaines;
mod user_ecoles;
mod user_entreprises;
mod user_langues;
mod user_localites;
mod user_specialites;
mod user_titres;

pub use campus::*;
pub use departements::*;
pub use competences::*;
pub use diplomes_certificats::*;
pub use domaines::*;
pub use ecoles::*;
pub use entreprises::*;
pub use langues::*;
pub use localite::*;
pub use specialites::*;
pub use titres::*;
pub use user_plus_infos::*;
pub use users::*;
pub use user_contact::*;
pub use user_campus::*;
pub use user_competences::*;
pub use user_department::*;
pub use user_diplomes::*;
pub use user_domaines::*;
pub use user_ecoles::*;
pub use user_entreprises::*;
pub use user_langues::*;
pub use user_localites::*;
pub use user_specialites::*;
pub use user_titres::*;

