[package]
name = "gateway"
version = "0.2.0"
edition = "2021"


[dependencies]
common = { version = "0.1", path = "../common" }
inter_services_messages = { version = "0.1", path = "../inter_services_messages" }